// Gate on the docs/scripts.md Index — a projection of each script's own first comment
// line, generated by scripts/gen-scripts-doc.ts.
//
// The table was hand-kept and had drifted to listing 15 of 47 scripts plus one
// (`scripts/foo.ts`) that never existed, so the doc that exists to stop contributors writing
// a duplicate was hiding two thirds of what already existed.
import { test, expect } from "bun:test";
import { readFileSync } from "fs";
import { trackedFiles } from "../scripts/gen-scripts-doc";
import { join } from "path";
import { execFileSync } from "child_process";

const ROOT = join(import.meta.dir, "..");

test("the checked-in index matches the generator", () => {
  // Regenerate with: bun run scripts/gen-scripts-doc.ts
  execFileSync("bun", ["run", "scripts/gen-scripts-doc.ts", "--check"], { cwd: ROOT, stdio: "pipe" });
});

test("every script is listed", () => {
  const doc = readFileSync(join(ROOT, "docs", "scripts.md"), "utf-8");
  const files = trackedFiles("scripts").filter(f => f.endsWith(".ts") || f.endsWith(".sh"));
  expect(files.length).toBeGreaterThan(30); // the scan must actually find the directory
  expect(files.filter(f => !doc.includes(`\`scripts/${f}\``))).toEqual([]);
});

test("no listed script is missing from disk", () => {
  const doc = readFileSync(join(ROOT, "docs", "scripts.md"), "utf-8");
  const listed = [...doc.matchAll(/\| `((?:scripts|\.githooks)\/[^`]+)` \|/g)].map(m => m[1]!);
  expect(listed.length).toBeGreaterThan(30);
  expect(listed.filter(p => !trackedFiles(p.split("/")[0]!).includes(p.split("/")[1]!))).toEqual([]);
});

test("no purpose line was truncated by the length cap", () => {
  // A cap hit means the script's own first sentence runs past 200 characters; the fix
  // is to tighten that sentence, not to widen the cap.
  const doc = readFileSync(join(ROOT, "docs", "scripts.md"), "utf-8");
  const truncated = doc.split("\n").filter(l => l.startsWith("| `") && l.includes("… |"));
  expect(truncated).toEqual([]);
});
