// Gates on the stdlib reference: docs/site/stdlib/<module>.md carries a region generated by
// scripts/gen-std-docs.ts from `milo api --json`, and hand-written prose around it.
import { test, expect } from "bun:test";
import { readFileSync, readdirSync } from "fs";
import { join } from "path";
import { apiEntries, builtinMembers, generate, pageOf, SITE_STDLIB, type ApiEntry } from "../scripts/gen-std-docs";

const entries = apiEntries();
const results = generate(entries, undefined, builtinMembers());

test("every stdlib page's generated regions match the std doc-comments", () => {
  // A generator that found no pages would pass the drift check vacuously.
  expect(results.length).toBeGreaterThan(70);
  const stale = results.filter(r => r.expected !== r.actual).map(r => r.file);
  expect(`stale: ${stale.join(", ") || "none"} (run: bun run scripts/gen-std-docs.ts)`)
    .toBe("stale: none (run: bun run scripts/gen-std-docs.ts)");
});

// Coverage ratchet: how many public std entries (types, functions, methods) carry no doc
// comment. It may only go DOWN: writing a doc-comment lowers it, adding an undocumented API
// raises it and fails here. Lower the baseline in the same commit that improves the docs.
// Counted from the payload, not the rendering, so a change to how the page shows an
// undocumented entry cannot move it. Each platform arm counts separately: an arm is its own
// source file with its own comments.
const UNDOCUMENTED_BASELINE = 677; // measured 2026-09-22, types included (the old count, 886, was functions only)

test("the undocumented-API count only goes down", () => {
  const undocumented = entries.filter(e => !e.docFull).length;
  // A payload that stopped carrying entries would report perfect coverage.
  expect(entries.length).toBeGreaterThan(1500);
  expect(`${undocumented} undocumented (baseline ${UNDOCUMENTED_BASELINE})`)
    .toBe(`${Math.min(undocumented, UNDOCUMENTED_BASELINE)} undocumented (baseline ${UNDOCUMENTED_BASELINE})`);
});

// The hand-written part of a page must not restate what the generated region already
// carries. A signature typed by hand is the text that drifted before: the argparse page
// documented a free-function API that was really methods on `ArgParser`, the process page a
// `Process.spawn(command)` that takes a program path, the json page a three-field `Json`
// struct against a real six-field one. Examples are fine; declarations are the region's job.
function handRestatements(page: string, text: string, stdTypes: Set<string>): string[] {
  const hand = text.replace(/<!-- generated:(\w+) -->[\s\S]*?<!-- \/generated:\1 -->/g, "");
  const out: string[] = [];
  for (const m of hand.matchAll(/```milo[^\n]*\n([\s\S]*?)```/g)) {
    const body = m[1]!.split("\n").map(l => l.trim()).filter(l => l && !l.startsWith("//"));
    if (!body.length) continue;
    if (body.every(l => /^(pub\s+)?fn\s+[A-Za-z_]/.test(l) && !l.includes("{"))) {
      out.push(`${page}: hand-written signature listing \`${body[0]}\``);
      continue;
    }
    for (const l of body) {
      const decl = /^(?:pub\s+)?(?:struct|enum)\s+([A-Za-z_][A-Za-z0-9_]*)/.exec(l);
      if (decl && stdTypes.has(decl[1]!)) out.push(`${page}: hand-written declaration of std type \`${decl[1]}\``);
    }
  }
  return out;
}

function typesByPage(all: ApiEntry[]): Map<string, Set<string>> {
  const out = new Map<string, Set<string>>();
  for (const e of all) {
    if (e.kind !== "type") continue;
    const set = out.get(pageOf(e.module)) ?? new Set<string>();
    set.add(e.name);
    out.set(pageOf(e.module), set);
  }
  return out;
}

test("no page restates a signature or a std type outside its generated region", () => {
  const types = typesByPage(entries);
  const problems: string[] = [];
  for (const f of readdirSync(SITE_STDLIB).filter(f => f.endsWith(".md") && f !== "index.md")) {
    const page = f.replace(/\.md$/, "");
    problems.push(...handRestatements(page, readFileSync(join(SITE_STDLIB, f), "utf-8"), types.get(page) ?? new Set()));
  }
  expect(problems).toEqual([]);
});

test("the restatement check actually reads fences", () => {
  // Fed a deliberate restatement of each kind, it must object; fed an example, it must not.
  const types = new Set(["Json"]);
  expect(handRestatements("json", "```milo\nfn Json.get(self: &Json, key: &string): Option<Json>\n```", types).length).toBe(1);
  expect(handRestatements("json", "```milo\nstruct Json {\n    raw: string,\n}\n```", types).length).toBe(1);
  expect(handRestatements("json", "```milo\nlet j = Json.parse(\"{}\")!\n```", types)).toEqual([]);
  // Inside a generated region a listing is expected, not a restatement.
  expect(handRestatements("json", "<!-- generated:api -->\n```milo\nfn Json.get(self: &Json): i64\n```\n<!-- /generated:api -->", types)).toEqual([]);
});
