// generates src/stdlib-bundle.ts with all std/*.milo files embedded as strings
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const stdDir = resolve(root, "std");
const outFile = resolve(root, "src", "stdlib-bundle.ts");

const files = readdirSync(stdDir).filter(f => f.endsWith(".milo")).sort();
const entries = files.map(f => {
  const content = readFileSync(resolve(stdDir, f), "utf-8");
  return `  [${JSON.stringify("std/" + f)}, ${JSON.stringify(content)}]`;
});

const code = `// auto-generated by scripts/bundle-stdlib.ts — do not edit
export const STDLIB: Map<string, string> = new Map([
${entries.join(",\n")}
]);
`;

writeFileSync(outFile, code);
console.log(`bundled ${files.length} stdlib files → src/stdlib-bundle.ts`);
