// Generates docs/errors.md — every compile error the test suite pins, with the program
// that provokes it.
//
// Run:  bun run scripts/gen-error-catalog.ts          # rewrite the catalog
//       bun run scripts/gen-error-catalog.ts --check  # fail if it is stale (CI/test)
//
// tests/errors/ already holds 242 programs, each annotated with the message it must
// produce and many with a comment explaining why the rule exists. That is a reference
// manual nobody could read: it was 242 files with no index, and a user hitting
// "cannot move out of a borrow" had nowhere to look it up. Nothing here is written by
// hand — improve an entry by improving the fixture's own comment.
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";
import { parseExpectedError } from "../tests/annotations";

const ROOT = join(import.meta.dir, "..");
const ERRORS_DIR = join(ROOT, "tests", "errors");
const OUT = join(ROOT, "docs", "errors.md");

interface ErrorCase {
  file: string;
  message: string;
  /** The fixture's own explanation, if it opens with one. */
  rationale: string;
  /** The program, with the annotation and rationale stripped. */
  program: string;
}

export function cases(): ErrorCase[] {
  const out: ErrorCase[] = [];
  for (const file of readdirSync(ERRORS_DIR).filter(f => f.endsWith(".milo")).sort()) {
    const source = readFileSync(join(ERRORS_DIR, file), "utf-8");
    const lines = source.split("\n");
    // The same parser the test driver uses, so the catalog and the gate can never
    // disagree about what a fixture asserts.
    const message = parseExpectedError(source);
    if (!message) throw new Error(`tests/errors/${file} has no // @error: annotation`);

    // Everything before the first non-comment, non-blank line is header: the
    // annotations plus, sometimes, a paragraph saying why the rule exists.
    let i = 0;
    const header: string[] = [];
    for (; i < lines.length; i++) {
      const t = lines[i]!.trim();
      if (t === "") { header.push(""); continue; }
      if (!t.startsWith("//")) break;
      header.push(t);
    }
    const rationale = header
      .filter(l => l.startsWith("//") && !/@(error|expect|skip-os|run)\b/.test(l))
      .map(l => l.replace(/^\/\/\s?/, ""))
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();

    out.push({ file, message: message.trim(), rationale, program: lines.slice(i).join("\n").trim() });
  }
  return out;
}

function byMessage(all: ErrorCase[]): Map<string, ErrorCase[]> {
  const m = new Map<string, ErrorCase[]>();
  for (const c of all) m.set(c.message, [...(m.get(c.message) ?? []), c]);
  return new Map([...m].sort((a, b) => a[0].localeCompare(b[0])));
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export function render(): string {
  const all = cases();
  const grouped = byMessage(all);
  const lines: string[] = [
    "<!-- doc-meta",
    "system: error-catalog",
    "purpose: every compile error the suite pins, with the program that provokes it and why the rule exists",
    "key-files: tests/errors/, scripts/gen-error-catalog.ts, src/diagnostics.ts",
    "update-when: never by hand — regenerate with `bun run scripts/gen-error-catalog.ts`",
    "last-verified: generated",
    "-->",
    "",
    "# Compile errors",
    "",
    `Generated from \`tests/errors/\` by \`scripts/gen-error-catalog.ts\` — ${grouped.size} distinct messages across ${all.length} pinned programs.`,
    "Each entry is a program the compiler must reject and the message it must produce.",
    "Do not edit this file; edit the fixture, or its leading comment, and regenerate.",
    "",
    "## Index",
    "",
  ];
  for (const msg of grouped.keys()) lines.push(`- [\`${msg}\`](#${slug(msg)})`);
  lines.push("");

  for (const [msg, group] of grouped) {
    lines.push(`## ${msg}`, "");
    for (const c of group) {
      if (c.rationale) lines.push(c.rationale, "");
      lines.push("```milo", c.program, "```", "");
      lines.push(`<sub>[\`tests/errors/${c.file}\`](../tests/errors/${c.file})</sub>`, "");
    }
  }
  return lines.join("\n");
}

if (import.meta.main) {
  const next = render();
  if (process.argv.includes("--check")) {
    let current = "";
    try { current = readFileSync(OUT, "utf-8"); } catch { /* not generated yet */ }
    if (current !== next) {
      console.error("docs/errors.md is stale — run: bun run scripts/gen-error-catalog.ts");
      process.exit(1);
    }
    console.log("docs/errors.md is up to date");
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT}`);
  }
}
