#!/bin/sh
# Build milo-self (the Milo compiler written in Milo) with the TS compiler.
# The TS compiler is the oracle; this script only produces the stage-1 binary.
# Exits nonzero if it does not build. See docs/self-hosting.md.
#
# The build runs under scripts/guard.ts so a runaway build can never eat all
# system memory (macOS enforces no rlimits — the guard is the only real cap).
#
# The REAL binary is .selfhost/milo-self.bin. .selfhost/milo-self is a
# self-guarding wrapper: any bare invocation gets the RSS
# watchdog automatically, so forgetting the guard can no longer crash the OS.
# Test harnesses call milo-self.bin directly via guardedRun (single guard).
set -e

root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/.selfhost"
mkdir -p "$out"

# --mem-mb is explicit, not left to the guard's default. The default is
# min(4096, RAM/4), so the SAME command enforced a different cap per machine: 4096 MB on a
# 16 GB dev Mac, 1792 MB on a 7 GB CI runner — where it SIGKILLed this build, produced no
# milo-self.bin, and surfaced as the fixpoint failing at stage 2 with "No such file or
# directory". A build's memory need is a property of the build, not of whoever runs it.
#
# The cap is on the process TREE, and this build's tree is not just bun: above ~40k IR lines
# the driver splits into codegen units and backgrounds one clang per unit, min(cores-2, 8).
# So peak tree RSS scales with the HOST's core count — 3072 held on a 2-core CI runner and
# SIGKILLed every run on a 10-core Mac (8 clangs), where the fixpoint then compared stage 2
# against a stale binary. Measured: bun peaks at 1.7 GB alone, the full tree fits in 4096 at
# 8 units, and that still sits under the guard's half-of-RAM backstop from 8 GB up. A cap
# meant to be a property of the build has to cover the widest host, not the narrowest.
bun "$root/scripts/guard.ts" --mem-mb 4096 --virtual-mem-mb 8192 --timeout-s 300 -- \
  bun run "$root/src/main.ts" build "$root/src-milo/main.milo" -o "$out/milo-self.bin" "$@"

# Record which source this binary came from. Every harness grades a binary it
# did not build; without this they cannot tell a fresh one from a stale one, and
# a stale one still produces a confident verdict. See scripts/selfhost-stamp.ts.
bun "$root/scripts/selfhost-stamp.ts" --write

cat > "$out/milo-self" <<EOF
#!/bin/sh
# Auto-generated by scripts/selfhost.sh. milo-self has known memory bugs;
# this wrapper forces every invocation through the RSS/timeout guard.
# Never run milo-self.bin bare.
exec bun "$root/scripts/guard.ts" -- "$out/milo-self.bin" "\$@"
EOF
chmod +x "$out/milo-self"
