// WCET flow-fact extraction.
//
// Worst-Case Execution Time tools (OTAWA, aiT, Bound-T) need an upper bound on
// every loop's iteration count to bound a path. They can't always infer these
// from the binary, so they accept "flow facts" — external annotations stating
// each loop's max trip count. Milo is unusually well-placed to emit them: its
// safety profiles already *require* bounded loops, and `for..in <range>` carries
// the bound syntactically.
//
// This module walks the AST and emits OTAWA-F4-style flow facts keyed by source
// location. Exact counts come from literal `for i in A..B` ranges; conservative
// upper bounds come from `while i < N` / `i <= N` with a literal N. Loops whose
// bound can't be read statically are reported as UNRESOLVED so the user knows
// the WCET analysis would be incomplete (silence would falsely imply coverage).

import type { Program, Stmt, Expr } from "./ast";

export interface LoopBound {
  fn: string;
  line: number;
  kind: "exact" | "max" | "unresolved";
  count: number | null;     // null when unresolved
  note: string;             // human-readable basis for the bound
}

export interface FlowFactResult {
  file: string;
  bounds: LoopBound[];
}

function intValue(e: Expr | undefined | null): number | null {
  if (e && e.kind === "IntLit") return e.value;
  return null;
}

// A loop counter `i < N` / `i <= N` against a literal gives an upper bound on
// iterations (assuming the counter starts at 0 and steps by 1 — the dominant
// idiom, and what the safety profile's bounded-loop invariants attest to).
function whileBound(cond: Expr): { count: number; note: string } | null {
  if (cond.kind !== "BinOp") return null;
  const rhs = intValue(cond.right);
  if (rhs === null) return null;
  if (cond.op === "<")  return { count: rhs,     note: `while ${exprName(cond.left)} < ${rhs}` };
  if (cond.op === "<=") return { count: rhs + 1, note: `while ${exprName(cond.left)} <= ${rhs}` };
  return null;
}

function exprName(e: Expr): string {
  return e.kind === "Ident" ? e.name : "<expr>";
}

function collectFromStmts(fn: string, stmts: Stmt[], out: LoopBound[]) {
  for (const s of stmts) collectFromStmt(fn, s, out);
}

function collectFromStmt(fn: string, s: Stmt, out: LoopBound[]) {
  switch (s.kind) {
    case "ForInStmt": {
      const line = s.span?.line ?? 0;
      if (s.iterable.kind === "RangeExpr") {
        const lo = intValue(s.iterable.start);
        const hi = intValue(s.iterable.end);
        if (lo !== null && hi !== null) {
          // `A..B` is exclusive of B (Milo range semantics): B - A iterations.
          out.push({ fn, line, kind: "exact", count: Math.max(0, hi - lo), note: `for in ${lo}..${hi}` });
        } else {
          out.push({ fn, line, kind: "unresolved", count: null, note: "for-in over non-literal range" });
        }
      } else {
        // for-in over a collection: bound is the collection length, not known here.
        out.push({ fn, line, kind: "unresolved", count: null, note: "for-in over collection (length not statically known)" });
      }
      collectFromStmts(fn, s.body, out);
      break;
    }
    case "WhileStmt": {
      const line = s.span?.line ?? 0;
      const b = whileBound(s.cond);
      if (b) out.push({ fn, line, kind: "max", count: b.count, note: b.note });
      else   out.push({ fn, line, kind: "unresolved", count: null, note: "while with non-literal bound" });
      collectFromStmts(fn, s.body, out);
      break;
    }
    case "IfStmt":
      collectFromStmts(fn, s.thenBody, out);
      if (s.elseBody) collectFromStmts(fn, s.elseBody, out);
      break;
    case "IfLetStmt":
      collectFromStmts(fn, s.thenBody, out);
      if (s.elseBody) collectFromStmts(fn, s.elseBody, out);
      break;
    case "MatchStmt":
      for (const arm of s.arms) collectFromStmts(fn, arm.body, out);
      break;
    case "UnsafeBlock":
      collectFromStmts(fn, s.body, out);
      break;
    default:
      break;
  }
}

export function extractFlowFacts(program: Program, file: string): FlowFactResult {
  const userFns = program.userFnNames;
  const bounds: LoopBound[] = [];
  for (const fn of program.functions) {
    if (fn.isExtern) continue;
    if (userFns && !userFns.has(fn.name)) continue;
    collectFromStmts(fn.name, fn.body, bounds);
  }
  return { file, bounds };
}

// Render OTAWA-F4-style textual flow facts keyed by source line. OTAWA's binary
// F4 form keys loops by address (symbol+offset), which isn't known pre-link;
// the SOURCE/LINE form here is consumed by OTAWA's source-line flow-fact path
// and is the portable representation to ship alongside the ELF.
export function formatFlowFacts(result: FlowFactResult): string {
  const lines: string[] = [];
  lines.push(`// OTAWA flow facts for ${result.file}`);
  lines.push(`// generated by milo — loop iteration bounds for WCET analysis`);
  lines.push(`// COUNT = exact, MAX = upper bound; UNRESOLVED loops need manual annotation`);
  lines.push("");
  if (result.bounds.length === 0) {
    lines.push("// no loops found");
    return lines.join("\n") + "\n";
  }
  for (const b of result.bounds) {
    if (b.kind === "unresolved") {
      lines.push(`// UNRESOLVED loop SOURCE "${result.file}" LINE ${b.line} ; // ${b.note}`);
    } else {
      const key = b.kind === "exact" ? "COUNT" : "MAX";
      lines.push(`loop SOURCE "${result.file}" LINE ${b.line} ${key} ${b.count} ; // in ${b.fn}: ${b.note}`);
    }
  }
  return lines.join("\n") + "\n";
}
